# Generated by Django 4.2.11 on 2026-05-05 23:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchQuery",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("query", models.CharField(max_length=300)),
                ("results_count", models.PositiveIntegerField()),
                (
                    "clicked_book",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalog.book",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "search_queries",
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="search_quer_created_02141d_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PageView",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("session_key", models.CharField(max_length=40)),
                ("page_url", models.CharField(max_length=500)),
                ("referrer", models.CharField(blank=True, max_length=500)),
                ("user_agent", models.CharField(max_length=500)),
                ("ip", models.GenericIPAddressField()),
                ("country", models.CharField(blank=True, max_length=100)),
                (
                    "book",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalog.book",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "page_views",
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="page_views_created_5023bb_idx"
                    ),
                    models.Index(fields=["book"], name="page_views_book_id_82a540_idx"),
                    models.Index(
                        fields=["session_key"], name="page_views_session_d3dc99_idx"
                    ),
                ],
            },
        ),
    ]
