# Generated by Django 4.2.11 on 2026-05-05 23:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserBookInteraction",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("view", "Ko'rish"),
                            ("purchase", "Xarid"),
                            ("wishlist", "Sevimli"),
                            ("review", "Sharh"),
                            ("read", "O'qish"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "score",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=3),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="catalog.book"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="book_interactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_book_interactions",
                "indexes": [
                    models.Index(
                        fields=["user", "interaction_type"],
                        name="user_book_i_user_id_c13501_idx",
                    ),
                    models.Index(
                        fields=["book"], name="user_book_i_book_id_f2190d_idx"
                    ),
                ],
            },
        ),
    ]
