# Generated by Django 4.2.11 on 2026-05-05 23:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("full_name", models.CharField(db_index=True, max_length=200)),
                ("slug", models.SlugField(max_length=250, unique=True)),
                ("bio", models.TextField(blank=True)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="authors/"),
                ),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("death_date", models.DateField(blank=True, null=True)),
                ("nationality", models.CharField(blank=True, max_length=100)),
                ("is_featured", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "authors",
                "ordering": ["full_name"],
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=300)),
                ("slug", models.SlugField(max_length=350, unique=True)),
                ("isbn", models.CharField(db_index=True, max_length=20, unique=True)),
                ("description", models.TextField()),
                ("short_description", models.CharField(max_length=500)),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "discount_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "discount_percentage",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("stock_quantity", models.PositiveIntegerField(default=0)),
                ("page_count", models.PositiveIntegerField()),
                (
                    "cover_type",
                    models.CharField(
                        choices=[
                            ("hardcover", "Qattiq muqova"),
                            ("softcover", "Yumshoq muqova"),
                        ],
                        default="softcover",
                        max_length=20,
                    ),
                ),
                ("weight_grams", models.PositiveIntegerField(blank=True, null=True)),
                ("dimensions", models.CharField(blank=True, max_length=50)),
                ("has_paperback", models.BooleanField(default=True)),
                ("has_ebook", models.BooleanField(default=False)),
                ("has_audiobook", models.BooleanField(default=False)),
                (
                    "ebook_file",
                    models.FileField(blank=True, null=True, upload_to="ebooks/"),
                ),
                (
                    "audiobook_file",
                    models.FileField(blank=True, null=True, upload_to="audiobooks/"),
                ),
                ("audiobook_duration", models.DurationField(blank=True, null=True)),
                ("publication_date", models.DateField()),
                ("edition", models.CharField(blank=True, max_length=50)),
                ("meta_title", models.CharField(blank=True, max_length=200)),
                ("meta_description", models.CharField(blank=True, max_length=300)),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("sold_count", models.PositiveIntegerField(default=0)),
                (
                    "average_rating",
                    models.DecimalField(decimal_places=2, default=0, max_digits=3),
                ),
                ("review_count", models.PositiveIntegerField(default=0)),
                ("is_published", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_bestseller", models.BooleanField(default=False)),
                ("is_new", models.BooleanField(default=False)),
                (
                    "authors",
                    models.ManyToManyField(related_name="books", to="catalog.author"),
                ),
            ],
            options={
                "db_table": "books",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=5, unique=True)),
                ("name", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "languages",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Publisher",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=200, unique=True)),
                ("slug", models.SlugField(max_length=250, unique=True)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="publishers/"),
                ),
                ("website", models.URLField(blank=True)),
            ],
            options={
                "db_table": "publishers",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=150, unique=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Lucide icon nomi", max_length=50
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="catalog.genre",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Genres",
                "db_table": "genres",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BookImage",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("image", models.ImageField(upload_to="books/")),
                ("is_primary", models.BooleanField(default=False)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.book",
                    ),
                ),
            ],
            options={
                "db_table": "book_images",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="BookCollection",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=250, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "cover_image",
                    models.ImageField(blank=True, null=True, upload_to="collections/"),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "books",
                    models.ManyToManyField(
                        related_name="collections", to="catalog.book"
                    ),
                ),
            ],
            options={
                "db_table": "book_collections",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="book",
            name="genres",
            field=models.ManyToManyField(related_name="books", to="catalog.genre"),
        ),
        migrations.AddField(
            model_name="book",
            name="language",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="books",
                to="catalog.language",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="publisher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="books",
                to="catalog.publisher",
            ),
        ),
        migrations.AddIndex(
            model_name="author",
            index=models.Index(fields=["slug"], name="authors_slug_63b8c8_idx"),
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(fields=["slug"], name="books_slug_0d7beb_idx"),
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(
                fields=["is_published", "is_featured"], name="books_is_publ_fd0438_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(
                fields=["is_published", "is_bestseller"],
                name="books_is_publ_fa26ea_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(
                fields=["is_published", "is_new"], name="books_is_publ_e42c0e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(fields=["price"], name="books_price_89e2a6_idx"),
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(
                fields=["average_rating"], name="books_average_90b5f0_idx"
            ),
        ),
    ]
